# Generated by Django 3.1.5 on 2021-01-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210117_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimages', verbose_name='Alternative Images'),
        ),
    ]
