# Generated by Django 3.1.5 on 2021-01-17 03:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210117_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alt_images',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimages',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
