# Generated by Django 3.1.5 on 2021-01-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
