# Generated by Django 3.1.5 on 2021-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
